stages:
  - build
  - test
  - integration_test
  - acceptance_test
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/your-username/your-repo:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

unit_test:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE go test ./... -v

integration_test:
  stage: integration_test
  script:
    - docker-compose -f docker-compose.integration.yml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.integration.yml down

acceptance_test:
  stage: acceptance_test
  script:
    - docker-compose -f docker-compose.acceptance.yml up --build --abort-on-container-exit
    - docker-compose -f docker-compose.acceptance.yml down

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  environment:
    name: production
    url: http://your-production-url
  only:
    - main
